name: "[CI] Continuous Integration"

#Sempre que tiver um commit ou um Pull Request for aberto
on: 
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latesd
        steps:
            - name: "Lint"
              run: "npm run lint"        
