name: "[CI] Continuous Integration"

#Sempre que tiver um commit ou um Pull Request for aberto
on: 
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            ## [Common_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependencies"
              run: "npm install"     
            - name: "Lint 4"
              run: "npm run lint"        
